[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
broadcast = "broadcast"
auto_detect_solc = false
bytecode_hash = "none"
emv_version = "paris"
fuzz = { runs = 1_000 }
optimizer = true
optimizer_runs = 10_000
solc = "0.8.22"
test = "test"

[rpc_endpoints]
localhost = "http://localhost:8545"
arbitrumGoerli = "${ARBITRUM_GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
arbitrumGoerli = { key = "${ARBITRUM_API_KEY}" }

[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_sequence = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# Remappings in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
