[profile.default]
src = "src"
out = "out"
libs = ["lib"]
broadcast = "broadcast"

[rpc_endpoints]
arbitrumGoerli = "${ARBITRUM_GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
arbitrumGoerli = { key = "${ARBITRUM_API_KEY}" }


[fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_sequence = true

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

# Remappings in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
