name: foundry test

on:
  push:
      branches:
        - main
  pull_request:
      branches:
        - "**"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: IncentiVibe Foundry Contract Tests
    runs-on: ubuntu-latest
    env:
      ARBITRUM_GOERLI_RPC_URL: ${{ secrets.ARBITRUM_GOERLI_RPC_URL }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        env:
          DEPLOYER_ADDRESS: ${{ secrets.DEPLOYER_ADDRESS }}
        run: |
          forge test -vvv --no-match-contract LockupLinearStreamCreatorTest
        id: test
